-- Optional dedicated demo database. Run with an explicitly authorized Snowflake role.
CREATE DATABASE IF NOT EXISTS FABRIC_DEMO;
CREATE SCHEMA IF NOT EXISTS FABRIC_DEMO.SALES;
CREATE TABLE IF NOT EXISTS FABRIC_DEMO.SALES.ORDERS (
    ORDER_ID VARCHAR(64), CUSTOMER_ID VARCHAR(64), PRODUCT_ID VARCHAR(64),
    ORDER_DATE TIMESTAMP_TZ, UPDATED_AT TIMESTAMP_TZ,
    QUANTITY INTEGER, UNIT_PRICE NUMBER(18,2), CURRENCY VARCHAR(3)
);
MERGE INTO FABRIC_DEMO.SALES.ORDERS target
USING (SELECT 'O100' AS ORDER_ID) source ON target.ORDER_ID = source.ORDER_ID
WHEN NOT MATCHED THEN INSERT VALUES ('O100', 'C01', 'P01', '2026-09-01 10:00:00 +00:00', '2026-09-01 11:00:00 +00:00', 3, 19.95, 'USD');
-- Fabric mirroring role/authentication, warehouse and source-specific prerequisites are separate.
